---
name: Deploy on aiscatcher changes

on:
  schedule:
      - cron: "*/30 * * * *"

# Set workflow-wide environment variables
#  - REPO: repo name on dockerhub
#  - IMAGE: image name on dockerhub
env:
#  DOCKERHUB_REPO: sdr-enthusiasts
#  DOCKERHUB_IMAGE: shipxplorer
  GHCR_IMAGE: sdr-enthusiasts/shipxplorer
  GHCR_REGISTRY: ghcr.io
  CHECK_CONTAINER: jvde-github/ais-catcher
  CHECK_TAG: edge

jobs:
  check_upstream_image:
    name: Check upstream image
    runs-on: ubuntu-latest
    steps:
      # Check out our code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Read package.json
          id: aiscatcher-sha
          uses: juliangruber/read-file-action@v1
          with:
              path: ./aiscatcher.sha
      - name: check container SHAs
          run:
              TOKEN="$(curl "https://ghcr.io/token?scope=repository:${CHECK_CONTAINER}:pull" | awk -F'"' '$0=$4')"
              manifest="$(curl -H "Authorization: Bearer ${TOKEN}" "https://ghcr.io/v2/${USER_IMAGE}/manifests/${CHECK_TAG}")"
              SHAs="$(echo $manifest|jq '.manifests[].digest')"
              SHAs="${manifest//$'\n'/}"
              # now compare:
              if [[ "${{ steps.aiscatcher-sha.outputs.content }}" != "$SHAs" ]]; then
                # we need to rebuild
                echo "$SHAs" > ./aiscatcher.sha
                git config --local user.name actions-user
                git config --local user.email "actions@github.com"
                git add ./aiscatcher.sha
                git commit -am "GH Action SHA updated $(date)"
                git push -f origin main
                echo "Success"
              else
                exit 1
              fi

  call-workflow-2-in-local-repo:
    needs: check_upstream_image
    uses: ./.github/workflows/deploy.yml
