---
name: Deploy on aiscatcher changes
on:
  schedule:
      - cron: "0,15,30,45 * * * *"
      - workflow_dispatch

# Set workflow-wide environment variables
#  - REPO: repo name on dockerhub
#  - IMAGE: image name on dockerhub
env:
#  DOCKERHUB_REPO: sdr-enthusiasts
#  DOCKERHUB_IMAGE: shipxplorer
  GHCR_IMAGE: sdr-enthusiasts/shipxplorer
  GHCR_REGISTRY: ghcr.io
  CHECK_CONTAINER: jvde-github/ais-catcher
  CHECK_TAG: edge

jobs:
  check_upstream_image:
    name: Check upstream image
    runs-on: ubuntu-latest
    steps:
      # Check out our code
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: check container SHAs
        env:
          CHECK_CONTAINER: ${{ env.CHECK_CONTAINER }}
          CHECK_TAG: ${{ env.CHECK_TAG }}
        run: bash ./tools/check_rebuild.sh

  call-workflow-2-in-local-repo:
    needs: check_upstream_image
    uses: ./.github/workflows/deploy.yml
